### ISSUE TITLE
livereload does nothing if no browser is watching

### ISSUE THREAD

**Issue by ralsina** [lepture/python-livereload#109]
We use livereload in http://getnikola.com to monitor site changes and trigger rebuilds.

When using ``nikola auto -b`` which calls livereload with ``open_url=True`` everything works normally.
However, when not using that, rebuilds are never triggered.

**Comment by d0ugal** [comment]
This surprised me too. I thought my setup had broken at one point but it turned out that I had just closed the browser window :)

I guess it happens because nothing is subscribed to the events?

**Comment by lepture** [comment]
It is designed this way. If no browser is listening on the change event, it will watch nothing.

**Comment by ralsina** [comment]
Would you take a patch to make that an option? It's really useful for us to trigger events even with no watchers.

**Comment by d0ugal** [comment]
Who are you triggering it for if there are no watchers?

**Comment by ralsina** [comment]
Keeping a site updated when files are uploaded, or edited via a web UI.

**Comment by d0ugal** [comment]
The issue is that if you start the server, edit files and *then* open the browser and visit your site, the changes wont be reflected. You need to do another save and trigger a new build for them to show up.

So yeah, I can see that this makes sense. I would prefer builds still happened. Or maybe they need to be triggered when browser starts listening?

**Comment by lepture** [comment]
@ralsina @d0ugal It works without browser open now.

**Comment by d0ugal** [comment]
Awesome!
