### ISSUE TITLE
AttributeError: 'function' object has no attribute 'repr_str'

### ISSUE THREAD

**Issue by P-EB** [lepture/python-livereload#171]
While running `python3 setup.py test`, I got the following traceback.

```
======================================================================
ERROR: test_watch_file (tests.test_watcher.TestWatcher)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/autopkgtest.2Pi2SP/build.cBN/python-livereload-2.5.2/tests/test_watcher.py", line 66, in test_watch_file
    rv = watcher.examine()
  File "/tmp/autopkgtest.2Pi2SP/build.cBN/python-livereload-2.5.2/livereload/watcher.py", line 92, in examine
    func.repr_str, delay))
AttributeError: 'function' object has no attribute 'repr_str'
```

The reason is that the test function add_count doesn't have its own repr_str defined.

**Comment by spanezz** [comment]
It looks like one can set arbitrary members of function objects, but not of object methods. Given this source:
```py
def foo():
    pass

foo.bar = 1

class Foo(object):
    def foo(self):
        pass

a = Foo()
a.foo.bar = 1
```

This is what happens when trying to set a member of a function:

```
$ python /tmp/foo.py
Traceback (most recent call last):
  File "/tmp/foo.py", line 11, in <module>
    a.foo.bar = 1
AttributeError: 'instancemethod' object has no attribute 'bar'

$ python3 /tmp/foo.py
Traceback (most recent call last):
  File "/tmp/foo.py", line 11, in <module>
    a.foo.bar = 1
AttributeError: 'method' object has no attribute 'bar'
```

This is breaking passing an object method as func in Server.watch, which is something I was relying on. 

For now, I had to change code like this:
```py
        server.watch(self.content_root, self.reload)
```
to this:
```py
        # see https://github.com/lepture/python-livereload/issues/171
        def do_reload():
            self.reload()
        server.watch(self.content_root, do_reload)
```

**Comment by P-EB** [comment]
There is a good reason for that. When an object is instanciated, the methods are bound to their instance, which create some constraints incompatible with arbitrary direct alteration. I guess this is the getattribute code of a bound method that differs and don't allow it.

Should you declare foo/reload as a static method it would work. But it's not always possible.

**Comment by williamjmorenor** [comment]
Just note that I am not hable to update this package because of this failing test:

+ /usr/bin/python3 setup.py test
running test
running egg_info
writing livereload.egg-info/PKG-INFO
writing dependency_links to livereload.egg-info/dependency_links.txt
writing entry points to livereload.egg-info/entry_points.txt
writing requirements to livereload.egg-info/requires.txt
writing top-level names to livereload.egg-info/top_level.txt
reading manifest file 'livereload.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'livereload.egg-info/SOURCES.txt'
running build_ext
test_watch_dir (tests.test_watcher.TestWatcher) ... ok
test_watch_file (tests.test_watcher.TestWatcher) ... ERROR
test_watch_glob (tests.test_watcher.TestWatcher) ... ok
test_watch_ignore (tests.test_watcher.TestWatcher) ... ok

======================================================================
ERROR: test_watch_file (tests.test_watcher.TestWatcher)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/wmoreno/paquetes/python-livereload/python-livereload-2.5.2/tests/test_watcher.py", line 66, in test_watch_file
    rv = watcher.examine()
  File "/home/wmoreno/paquetes/python-livereload/python-livereload-2.5.2/livereload/watcher.py", line 92, in examine
    func.repr_str, delay))
AttributeError: 'function' object has no attribute 'repr_str'

----------------------------------------------------------------------
Ran 4 tests in 3.016s

FAILED (errors=1)
Test failed: <unittest.runner.TextTestResult run=4 errors=1 failures=0>
error: Test failed: <unittest.runner.TextTestResult run=4 errors=1 failures=0>
error: Bad exit status from /var/tmp/rpm-tmp.p7i0VU (%check)
    Bad exit status from /var/tmp/rpm-tmp.p7i0VU (%check)


Las good build is with version 2.5.1 available here:
https://koji.fedoraproject.org/koji/buildinfo?buildID=1094433

This was build 4 days ago and test passed fine with python3.7

**Comment by williamjmorenor** [comment]
Reference : 

https://bugzilla.redhat.com/show_bug.cgi?id=1574127
